name: Project Card Color Update

on:
  project_card:
    types: [moved]

jobs:
  color_card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const columnName = context.payload.project_card.column_name;
            const issue_number = context.payload.project_card.content_url.split('/').pop();

            let label = '';
            if (columnName === "Todo") label = "green";
            if (columnName === "BUGZZZ") label = "blue";
            if (columnName === "In Progress") label = "yellow";
            if (columnName === "Done") label = "purple";
            if (columnName === "Pushed to main") label = "red";

            await github.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: [label]
            });
